In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 

from matplotlib import pyplot as plt 

%matplotlib inline

In [2]:
df = pd.read_csv('H1.csv')

In [5]:
df.head().T

,0,1,2,3,4
IsCanceled,0,0,0,0,0
LeadTime,342,737,7,13,14
ArrivalDateYear,2015,2015,2015,2015,2015
ArrivalDateMonth,July,July,July,July,July
ArrivalDateWeekNumber,27,27,27,27,27
ArrivalDateDayOfMonth,1,1,1,1,1
StaysInWeekendNights,0,0,0,0,0
StaysInWeekNights,0,0,1,1,2
Adults,2,2,1,1,2
Children,0,0,0,0,0
Babies,0,0,0,0,0
Meal,BB,BB,BB,BB,BB
Country,PRT,PRT,GBR,GBR,GBR
MarketSegment,Direct,Direct,Direct,Corporate,Online TA
DistributionChannel,Direct,Direct,Direct,Corporate,TA/TO
IsRepeatedGuest,0,0,0,0,0
PreviousCancellations,0,0,0,0,0
PreviousBookingsNotCanceled,0,0,0,0,0
ReservedRoomType,C,C,A,A,A
AssignedRoomType,C,C,C,A,A
BookingChanges,3,4,0,0,0
DepositType,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit
Agent,NULL,NULL,NULL,304,240
Company,NULL,NULL,NULL,NULL,NULL
DaysInWaitingList,0,0,0,0,0
CustomerType,Transient,Transient,Transient,Transient,Transient
ADR,0,0,75,75,98
RequiredCarParkingSpaces,0,0,0,0,0
TotalOfSpecialRequests,0,0,0,0,1
ReservationStatus,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out
ReservationStatusDate,2015-07-01,2015-07-01,2015-07-02,2015-07-02,2015-07-03

In [4]:
df.tail().T

,40055,40056,40057,40058,40059
IsCanceled,0,0,0,0,0
LeadTime,212,169,204,211,161
ArrivalDateYear,2017,2017,2017,2017,2017
ArrivalDateMonth,August,August,August,August,August
ArrivalDateWeekNumber,35,35,35,35,35
ArrivalDateDayOfMonth,31,30,29,31,31
StaysInWeekendNights,2,2,4,4,4
StaysInWeekNights,8,9,10,10,10
Adults,2,2,2,2,2
Children,1,0,0,0,0
Babies,0,0,0,0,0
Meal,BB,BB,BB,HB,HB
Country,GBR,IRL,IRL,GBR,DEU
MarketSegment,Offline TA/TO,Direct,Direct,Offline TA/TO,Offline TA/TO
DistributionChannel,TA/TO,Direct,Direct,TA/TO,TA/TO
IsRepeatedGuest,0,0,0,0,0
PreviousCancellations,0,0,0,0,0
PreviousBookingsNotCanceled,0,0,0,0,0
ReservedRoomType,A,E,E,D,A
AssignedRoomType,A,E,E,D,A
BookingChanges,1,0,0,0,0
DepositType,No Deposit,No Deposit,No Deposit,No Deposit,No Deposit
Agent,143,250,250,40,69
Company,NULL,NULL,NULL,NULL,NULL
DaysInWaitingList,0,0,0,0,0
CustomerType,Transient,Transient-Party,Transient,Contract,Transient
ADR,89.75,202.27,153.57,112.8,99.06
RequiredCarParkingSpaces,0,0,0,0,0
TotalOfSpecialRequests,0,1,3,1,0
ReservationStatus,Check-Out,Check-Out,Check-Out,Check-Out,Check-Out
ReservationStatusDate,2017-09-10,2017-09-10,2017-09-12,2017-09-14,2017-09-14

In [6]:
df[['ArrivalDateYear', 'ArrivalDateWeekNumber']].isna().sum()

ArrivalDateYear          0
ArrivalDateWeekNumber    0
dtype: int64

In [8]:
df[['ArrivalDateYear', 'ArrivalDateWeekNumber']].describe().style.set_precision(0)

In [12]:
df['ArrivalDateYearWeek'] = df['ArrivalDateYear'].astype(str) + df['ArrivalDateWeekNumber'].astype(str)

201618    575
201643    528
201722    519
201715    476
201644    475
         ...
20165     181
201527    177
201550    173
201551    172
20161      85
Name: ArrivalDateYearWeek, Length: 115, dtype: int64

In [14]:
dfweeks = df[['ArrivalDateYearWeek', 'IsCanceled']].groupby('ArrivalDateYearWeek').sum()

In [16]:
dfweeks.head()

                     IsCanceled
ArrivalDateYearWeek
201527                       41
201528                       48
201529                       87
201530                       74
201531                      101